apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ssh-honeypot
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - ssh-honeypot
  selector:
    matchLabels:
      app: ssh-honeypot
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s