apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-honeypot
  namespace: ssh-honeypot
spec:
  replicas: 1

  strategy:
    type: Recreate
    
  selector:
    matchLabels:
      app: ssh-honeypot
  template:
    metadata:
      labels:
        app: ssh-honeypot
    spec:
      containers:
        - name: ssh-honeypot
          image: ssh-honeypot:local
          imagePullPolicy: Never

          ports:
            - name: ssh
              containerPort: 2222
              hostPort: 2222
            - name: metrics
              containerPort: 8000
              hostPort: 8000

          envFrom:
            - configMapRef:
                name: honeypot-config
            - secretRef:
                name: honeypot-secret

          readinessProbe:
            tcpSocket:
              port: 2222
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 2222
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"