apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-honeypot
  namespace: ssh-honeypot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-honeypot
  template:
    metadata:
      labels:
        app: ssh-honeypot
    spec:
      containers:
        - name: ssh-honeypot
          image: ssh-honeypot:local
          imagePullPolicy: Never
          ports:
            - name: ssh
              containerPort: 2222
              hostPort: 2222
            - name: metrics
              containerPort: 8000
              hostPort: 8000
          env:
            - name: POSTGRES_DB
              value: "honeypot"
            - name: POSTGRES_USER
              value: "honeypot"
            - name: POSTGRES_PASSWORD
              value: "honeypot"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"