apiVersion: v1
kind: Service
metadata:
  name: ssh-honeypot
  namespace: ssh-honeypot
  labels:
    app: ssh-honeypot
spec:
  type: ClusterIP
  selector:
    app: ssh-honeypot
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
    - name: metrics
      port: 8000
      targetPort: 8000