{
 "title": "SSH Honeypot",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Attempts",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "honeypot_total_attempts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Credentials",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "honeypot_total_credentials", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unique IPs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "honeypot_unique_ips", "legendFormat": "__auto" }
   ]
  }
 ]
}